# All keymaps:
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml

# !!! FOR KEYBIND HELP: ~

# ---------- CUSTOM KEYBINDS --------------

# TODO: unarchive, remove-spaces, fzf jump to (/copy to/ move to) dir

[manager]

prepend_keymap = [
    # FIXME: --sync is deprecated
    { on = "H", run = "plugin --sync hide-preview", desc = "Hide or show preview" },
    # { on = "l", run  = "plugin --sync fast-enter", desc = "Enter the subfolder faster, or open the file directly" },
    { on = "z", run = "plugin fzf", desc = "Jump to a directory or reveal a file using fzf" }, # override zoxide
    # ------ execute ------
    { on = [
        "e",
        "c",
    ], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = [
        "e",
        "r",
    ], run = '''shell 'remove-space-filename.sh "$0"' --confirm''', desc = "Remove spaces from filename" },
    { on = [
        "e",
        "d",
    ], run = '''shell 'ripdrag -a "$@" -x 2>/dev/null &' --confirm''', desc = "drag&drop" },
    # ------ jump to dir ------
    { on = [
        "g",
        "m",
    ], run = "cd /mnt", desc = "Go to mounted dirs" },
    { on = [
        "g",
        "D",
    ], run = "cd ~/dox", desc = "Go to dox" },
    { on = [
        "g",
        ".",
    ], run = "cd ~/repos/dotfiles", desc = "Go to dotfiles" },
    { on = [
        "g",
        "r",
    ], run = "cd ~/repos", desc = "Go to repos" },
    { on = [
        "g",
        "f",
    ], run = "cd ~/dox/fit", desc = "Go to Fit" },
    { on = [
        "g",
        "p",
    ], run = "cd ~/pix", desc = "Go to pix" },
    { on = [
        "g",
        "d",
    ], run = [
        "cd ~/Downloads",
        "sort mtime --reverse",
    ], desc = "Go to Downloads" },
    { on = [
        "g",
        "s",
    ], run = [
        "cd ~/pix/screens",
        "sort mtime --reverse",
    ], desc = "Go to screenshots" },
]

# Image scaling to max doesnt work
# [[manager.prepend_keymap]]
# on   = [ "T" ]
# run  = "plugin --sync max-preview"
# desc = "Maximize or restore preview"

# Other not used plugins: smart filter, jump to char
