# All keymaps:
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

# !!! FOR KEYBIND HELP: ~

# ---------- CUSTOM KEYBINDS --------------

# TODO: unarchive, fzf jump to (/copy to/ move to) dir

[manager]

prepend_keymap = [
    # ------ EXECUTE SHELL SCRIPTS------
    { on = [
        "e",
        "r",
    ], run = '''shell 'remove-space-filename.sh "$0"' --confirm''', desc = "Remove spaces from filename" },
    { on = [
        "e",
        "d",
    ], run = '''shell 'ripdrag -a "$@" -x 2>/dev/null &' --confirm''', desc = "drag&drop" },

    # ------ FZF JUMP ------
    { on = "z", run = '''shell 'ya emit cd $(fd --type directory --hidden | fzf)' --block''', desc = "fzf: search directories" }, # only directories
    { on = "Z", run = "plugin fzf", desc = "fzf: reveal a file" },

    # ------ PLUGINS ------
    { on = "m", run = "plugin relative-motions", desc = "Trigger new VIM relative motion" }, # TODO: show relative line numbers only on command
    { on = [
        "e",
        "C",
    ], run = "plugin ouch", desc = "Compress with ouch" },
    { on = [
        "e",
        "c",
    ], run = "plugin chmod", desc = "Chmod on selected files" },
    { on = "U", run = "plugin restore", desc = "Restore last deleted files/dirs" },

    { on = "M", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
    { on = "T", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },

    # ------ GOTO DIR ------
    { on = [
        "g",
        "m",
    ], run = "cd /mnt", desc = "Go to mounted dirs" },
    { on = [
        "g",
        "D",
    ], run = "cd ~/dox", desc = "Go to dox" },
    { on = [
        "g",
        ".",
    ], run = "cd ~/repos/dotfiles", desc = "Go to dotfiles" },
    { on = [
        "g",
        "r",
    ], run = "cd ~/repos", desc = "Go to repos" },
    { on = [
        "g",
        "f",
    ], run = "cd ~/dox/fit", desc = "Go to Fit" },
    { on = [
        "g",
        "p",
    ], run = "cd ~/pix", desc = "Go to pix" },
    { on = [
        "g",
        "d",
    ], run = [
        "cd ~/Downloads",
        "sort mtime --reverse",
    ], desc = "Go to Downloads" },
    { on = [
        "g",
        "s",
    ], run = [
        "cd ~/pix/screens",
        "sort mtime --reverse",
    ], desc = "Go to screenshots" },
]
