
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio = [3, 8, 8]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true

[preview]
max_width = 1700
max_height = 1000

[plugin]

prepend_fetchers = [
    # faster mime types fetching (O(1) from table) on remote
    { id = "mime", name = "/mnt/**", run = "mime-ext", prio = "high" },
]
# disable previews for remote mounted dirs (would need to be fetched)
prepend_preloaders = [{ name = "/mnt/**", run = "noop" }]

# custom previewers
prepend_previewers = [
    { name = "/mnt/**", run = "noop" },
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
]

# options when pressing "o" or "O"
[opener]
extract = [
    { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
display_image = [
    { run = 'feh -F -Z --start-at "$0"', orphan = true, desc = "feh", for = "unix" },
    { run = 'gwenview "$0"', orphan = true, desc = "gwenview", for = "unix" },
]
display_pdf = [
    { run = 'zathura "$0"', orphan = true, desc = "zathura", for = "unix" },
    { run = 'okular "$0"', orphan = true, desc = "okular", for = "unix" },
]

[open]
prepend_rules = [
    { mime = "image/*", use = "display_image" },
    { mime = "application/pdf", use = "display_pdf" },
]
