
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [3, 8, 8]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true

[preview]
max_width = 1700
max_height = 1000

[plugin]
prepend_previewers = [
    # Markdown
    { name = "*.md", run = "glow" },
    # Archive previewer
    { mime = "application/*zip", run = "ouch" },
    { mime = "application/x-tar", run = "ouch" },
    { mime = "application/x-bzip2", run = "ouch" },
    { mime = "application/x-7z-compressed", run = "ouch" },
    { mime = "application/x-rar", run = "ouch" },
    { mime = "application/x-xz", run = "ouch" },
    { mime = "application/xz", run = "ouch" },
]

# options when pressing "o" or "O"
[opener]
extract = [
    { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
display = [
    { run = 'feh -F -Z --start-at "$0"', orphan = true, desc = "Display with feh", for = "unix" },
]

[open]
prepend_rules = [{ mime = "image/*", use = "display" }]
