# adds blank line when new shell opened
add_newline = false 

format = '${custom.yazi}$all'


[custom.yazi]
description = "Indicate the shell was launched by `yazi`"
symbol = " "
when = """ test -n "$YAZI_LEVEL" """
